### ISSUE TITLE
Cannot subscribe to the newsletter with Chrome on MacOS

### ISSUE THREAD

**Issue by fjanon** [ballerina-platform/ballerina-dev-website#3093]
"Subscribe" button enabled but doesn't perform any action

Chrome Version 96.0.4664.45 (Official Build) (x86_64)

Chrome console:

07:36:13.847 DevTools failed to load source map: Could not load content for https://ballerina.io/css/bootstrap-theme.min.css.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
07:36:13.899 DevTools failed to load source map: Could not load content for https://ballerina.io/css/bootstrap.min.css.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
07:36:14.421 latest-jquery.js:2 jQuery.Deferred exception: initCodeLineNumbers is not defined ReferenceError: initCodeLineNumbers is not defined
    at HTMLDocument.<anonymous> (https://ballerina.io/js/ballerina-common.js?100:306:5)
    at e (https://ballerina.io/js/latest-jquery.js:2:30038)
    at t (https://ballerina.io/js/latest-jquery.js:2:30340) undefined
S.Deferred.exceptionHook @ latest-jquery.js:2
t @ latest-jquery.js:2
setTimeout (async)
(anonymous) @ latest-jquery.js:2
c @ latest-jquery.js:2
fireWith @ latest-jquery.js:2
fire @ latest-jquery.js:2
c @ latest-jquery.js:2
fireWith @ latest-jquery.js:2
ready @ latest-jquery.js:2
B @ latest-jquery.js:2
07:36:14.467 jquery-3.6.0.min.js:2 jQuery.Deferred exception: n.size is not a function TypeError: n.size is not a function
    at HTMLLIElement.<anonymous> (https://ballerina.io/js/abixTreeList.min.js:1:545)
    at Function.each (https://code.jquery.com/jquery-3.6.0.min.js:2:3003)
    at S.fn.init.each (https://code.jquery.com/jquery-3.6.0.min.js:2:1481)
    at o.init (https://ballerina.io/js/abixTreeList.min.js:1:492)
    at new o (https://ballerina.io/js/abixTreeList.min.js:1:176)
    at HTMLUListElement.<anonymous> (https://ballerina.io/js/abixTreeList.min.js:1:2276)
    at Function.each (https://code.jquery.com/jquery-3.6.0.min.js:2:3003)
    at S.fn.init.each (https://code.jquery.com/jquery-3.6.0.min.js:2:1481)
    at S.fn.init.e.fn.<computed> [as abixTreeList] (https://ballerina.io/js/abixTreeList.min.js:1:2206)
    at HTMLDocument.<anonymous> (https://ballerina.io/community/:1696:28) undefined
S.Deferred.exceptionHook @ jquery-3.6.0.min.js:2
t @ jquery-3.6.0.min.js:2
setTimeout (async)
(anonymous) @ jquery-3.6.0.min.js:2
c @ jquery-3.6.0.min.js:2
fireWith @ jquery-3.6.0.min.js:2
fire @ jquery-3.6.0.min.js:2
c @ jquery-3.6.0.min.js:2
fireWith @ jquery-3.6.0.min.js:2
ready @ jquery-3.6.0.min.js:2
B @ jquery-3.6.0.min.js:2
07:36:14.546 latest-jquery.js:2 Uncaught ReferenceError: initCodeLineNumbers is not defined
    at HTMLDocument.<anonymous> (ballerina-common.js?100:306)
    at e (latest-jquery.js:2)
    at t (latest-jquery.js:2)
(anonymous) @ ballerina-common.js?100:306
e @ latest-jquery.js:2
t @ latest-jquery.js:2
setTimeout (async)
S.readyException @ latest-jquery.js:2
(anonymous) @ latest-jquery.js:2
e @ latest-jquery.js:2
t @ latest-jquery.js:2
setTimeout (async)
(anonymous) @ latest-jquery.js:2
c @ latest-jquery.js:2
fireWith @ latest-jquery.js:2
fire @ latest-jquery.js:2
c @ latest-jquery.js:2
fireWith @ latest-jquery.js:2
t @ latest-jquery.js:2
setTimeout (async)
(anonymous) @ latest-jquery.js:2
c @ latest-jquery.js:2
fireWith @ latest-jquery.js:2
fire @ latest-jquery.js:2
c @ latest-jquery.js:2
fireWith @ latest-jquery.js:2
ready @ latest-jquery.js:2
B @ latest-jquery.js:2
07:36:14.600 jquery-3.6.0.min.js:2 Uncaught TypeError: n.size is not a function
    at HTMLLIElement.<anonymous> (abixTreeList.min.js:1)
    at Function.each (jquery-3.6.0.min.js:2)
    at S.fn.init.each (jquery-3.6.0.min.js:2)
    at o.init (abixTreeList.min.js:1)
    at new o (abixTreeList.min.js:1)
    at HTMLUListElement.<anonymous> (abixTreeList.min.js:1)
    at Function.each (jquery-3.6.0.min.js:2)
    at S.fn.init.each (jquery-3.6.0.min.js:2)
    at S.fn.init.e.fn.<computed> [as abixTreeList] (abixTreeList.min.js:1)
    at HTMLDocument.<anonymous> ((index):1696)
(anonymous) @ abixTreeList.min.js:1
each @ jquery-3.6.0.min.js:2
each @ jquery-3.6.0.min.js:2
o.init @ abixTreeList.min.js:1
o @ abixTreeList.min.js:1
(anonymous) @ abixTreeList.min.js:1
each @ jquery-3.6.0.min.js:2
each @ jquery-3.6.0.min.js:2
e.fn.<computed> @ abixTreeList.min.js:1
(anonymous) @ (index):1696
e @ jquery-3.6.0.min.js:2
t @ jquery-3.6.0.min.js:2
setTimeout (async)
S.readyException @ jquery-3.6.0.min.js:2
(anonymous) @ jquery-3.6.0.min.js:2
e @ jquery-3.6.0.min.js:2
t @ jquery-3.6.0.min.js:2
setTimeout (async)
(anonymous) @ jquery-3.6.0.min.js:2
c @ jquery-3.6.0.min.js:2
fireWith @ jquery-3.6.0.min.js:2
fire @ jquery-3.6.0.min.js:2
c @ jquery-3.6.0.min.js:2
fireWith @ jquery-3.6.0.min.js:2
t @ jquery-3.6.0.min.js:2
setTimeout (async)
(anonymous) @ jquery-3.6.0.min.js:2
c @ jquery-3.6.0.min.js:2
fireWith @ jquery-3.6.0.min.js:2
fire @ jquery-3.6.0.min.js:2
c @ jquery-3.6.0.min.js:2
fireWith @ jquery-3.6.0.min.js:2
ready @ jquery-3.6.0.min.js:2
B @ jquery-3.6.0.min.js:2

**Comment by praneesha** [comment]
This is fixed via https://github.com/ballerina-platform/ballerina-dev-website/pull/3131.
